[[redirects]]
  from = "/api"
  to = "https://pro-api.coinmarketcap.com"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "VITE_ACCESS_TOKEN"